#配置文件
MODEL:
  META_ARCHITECTURE: 'MBU_BASELINE'

  OPEN_LAYERS: ""

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 2
    PRETRAIN: False

  HEADS:
    NAME: "BNneckHead"
    CLS_LAYER: "linear"
    POOL_LAYER: "gempool"
    NUM_CLASSES: 490

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")

    CE:
      EPSILON: 0.1
      SCALE: 1.0

    TRI:
      MARGIN: 1.2
      HARD_MINING: True
      USE_COSINE_DIST: True
      SCALE: 1.0

DATASETS:
  NAMES: ("celeb_reid_light",)
  TESTS: ("celeb_reid_light",)
  DATASETS_ROOT: "./data/celeb_reid_light"
  STN_ROOT: "./stn/model_best_stn.pth"

INPUT:
  SIZE_TRAIN: [256,192]
  SIZE_TEST: [256,192]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 0


SOLVER:
  OPT: "Adam"
  MAX_ITER: 15000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 32

  STEPS: [3520, 6160]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 880

  LOG_PERIOD: 880
  CHECKPOINT_PERIOD: 880

TEST:
  EVAL_PERIOD: 1000
  IMS_PER_BATCH: 32

CUDNN_BENCHMARK: True

OUTPUT_DIR: "logs/MBU_reid"
