_BASE_: "Base-MBU.yml"

MODEL:
  META_ARCHITECTURE: 'MBU_BASELINE'
  
  HEADS:
    NUM_CLASSES: 632
    
SOLVER:
  OPT: "Adam"
  MAX_ITER: 9000
  
  STEPS: [3520, 6160]
  
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 880

  LOG_PERIOD: 880
  CHECKPOINT_PERIOD: 880
  
TEST:
  EVAL_PERIOD: 1000
  IMS_PER_BATCH: 256

OUTPUT_DIR: "logs/MBU_baseline"